### ISSUE TITLE
pyds9/DS9 does not work in astroconda by default

### ISSUE THREAD

**Issue by mdhimes** [astroconda/astroconda#86]
Hi,

Confirmed problem for Ubuntu 18.04.1, 18.04.2, 18.04.3, and Mac 10.14.2.

Building the astroconda environment as instructed at https://astroconda.readthedocs.io/en/latest/installation.html does not raise any problems.  However, DS9 does not work.

Code to test if DS9 works:
python
> import pyds9
> ds9 = pyds9.DS9()

Trying to spawn DS9 via pyds9 results in an error about missing shared library files:
/home/USERNAME/anaconda3/envs/ENVNAME/bin/ds9: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/pyds9/pyds9.py", line 514, in __init__
    raise ValueError('no active ds9 running for target: %s' % target)
ValueError: no active ds9 running for target: ds9

Fixing this throws a similar error for libcrypto.so.10.

My patch for this:
conda install openssl=1.0
cd /home/USERNAME/anaconda3/envs/ENVNAME/lib/
sudo ln -s libssl.so.1.0.0 libssl.so.10
sudo ln -s libcrypto.so.1.0.0 libcrypto.so.10

This allows DS9 to work. However, it still has some minor problems. It throws warnings:
/home/USERNAME/anaconda3/envs/ENVNAME/bin/ds9: /home/USERNAME/anaconda3/envs/ENVNAME/bin/../lib/libcrypto.so.10: no version information available (required by /home/USERNAME/anaconda3/envs/ENVNAME/bin/ds9)
/home/USERNAME/anaconda3/envs/ENVNAME/bin/ds9: /home/USERNAME/anaconda3/envs/ENVNAME/bin/../lib/libssl.so.10: no version information available (required by /home/USERNAME/anaconda3/envs/ENVNAME/bin/ds9)

Then, after a moment, what appears to be an error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/pyds9/pyds9.py", line 514, in __init__
    raise ValueError('no active ds9 running for target: %s' % target)
ValueError: no active ds9 running for target: ds9

And then shortly after, DS9 will open. Executing the pyds9.DS9() command again will then properly link it, and it works without issue. A workaround is to launch DS9 before starting a Python session, and then linking it after it opens.

Can the developers patch this?

**Comment by kakirastern** [comment]
I think the problem has been fixed? I was able to install IRAF/PyRAF with the "pyds9/ds9 in astroconda by default" today.

**Comment by Knusper** [comment]
in debian 10 I get the following error when attempting to run ds9:

`ds9: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory`  

and I have the latest version - so clearly not fixed!
```

conda list ds9

# Name                    Version                   Build  Channel
ds9                       8.0.1                         0    http://ssb.stsci.edu/astroconda
pyds9                     1.9.0.dev145+gc1bf67a          py36_2    http://ssb.stsci.edu/astroconda

```

**Comment by Knusper** [comment]
Hi, I just updated ds9 from the astroconda channel with the new version and now I get a memory error:

```
Error in startup script: bad screen distance "1.0i"
    (default value for "-padx" in widget ".ds9.horz")
    (default value for "-pixels" in widget ".ds9.horz")
    invoked from within
"blt::graph $ds9(main).horz  -width $canvas(width) -height $igraph(size)  -taError in startup script: bad screen distance "1.0i"
    (default value for "-padx" in widget ".ds9.horz")
    (default value for "-pixels" in widget ".ds9.horz")
    invoked from within
"blt::graph $ds9(main).horz  -width $canvas(width) -height $igraph(size)  -takefocus 0  -background $ds9(background)  -plotbackground $ds9(background) ..."
    (procedure "CreateGraphs" line 8)
    invoked from within
"CreateGraphs"
    (file "zipfs:/mntpt/library/ds9.tcl" line 531)
Speicherzugriffsfehler
kefocus 0  -background $ds9(background)  -plotbackground $ds9(background) ..."
    (procedure "CreateGraphs" line 8)
    invoked from within
"CreateGraphs"
    (file "zipfs:/mntpt/library/ds9.tcl" line 531)
Memory Error
```

**Comment by jhunkeler** [comment]
My apologies for not seeing this until now. Out of curiosity... Does it still fail if you set your locale to C?

```
$ export LANG=C
$ export LC_NUMERIC=C
$ ds9
```

**Comment by Knusper** [comment]
> My apologies for not seeing this until now. Out of curiosity... Does it still fail if you set your locale to C?
> 
> ```
> $ export LANG=C
> $ export LC_NUMERIC=C
> $ ds9
> ```

No, with this locale settings it works fine.  My normal  locale is:
```
-> echo $LANG
de_DE.UTF-8
```
